name: Build

on:
  push:
    branches:
      - v0.3.5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.2

      - name: Install Start SDK 0.3.5
        run: |
          git clone --depth 1 -b v0.3.5.1 https://github.com/Start9Labs/start-os.git
          cd start-os/backend
          ./install-sdk.sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Build Docker image
        run: |
          mkdir -p docker-images
          docker buildx build --tag start9/feedview-relay/main:0.3.5.0 --platform=linux/arm64 -o type=docker,dest=docker-images/aarch64.tar .

      - name: Bundle scripts
        run: |
          deno bundle scripts/embassy.ts scripts/embassy.js

      - name: Pack s9pk
        run: |
          start-sdk pack

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: feedview-relay
          path: "*.s9pk"
