name: Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: start9labs/sdk@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARM64 Docker
        run: |
          mkdir -p docker-images
          docker buildx build --tag start9/feedview-relay/main:0.1.0 --platform=linux/arm64 -o type=docker,dest=docker-images/aarch64.tar .

      - name: Install dependencies and build TypeScript
        run: |
          npm ci
          npm run build

      - name: Pack s9pk
        run: |
          start-cli init-key
          start-cli s9pk pack

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: feedview-relay
          path: "*.s9pk"
